Models/Demand.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CarpooliDotTN.Models
{
    public class Demand
    {
        
        public Guid Id { get; set; }
        
        [ForeignKey("Passenger")]
        public string PassengerId { get; set; }
        
        [ForeignKey("Carpool")]
        public Guid CarpoolId { get; set; }
        public enum Response { pending,accepted,refused,cancelled }
        public Response status { get; set; }
        public DateTime SubmissionTime { get; set; }
        [InverseProperty("Demands")]
        public virtual Carpool Carpool { get; set; }
        public virtual User Passenger { get; set; }
    }
}

Controllers/DemandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CarpooliDotTN.DAL.IServices;
using CarpooliDotTN.Models;
using CarpooliDotTN.Services;
using CarpooliDotTN.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Authorize]
public class DemandController : Controller
{
    private readonly IDemandService _demandService;
    private readonly ICarpoolService _carpoolService;

    public string GetCurrentUser()
    {
        return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";
    }

    public DemandController(IDemandService demandService, ICarpoolService carpoolService)
    {
        _demandService = demandService;
        _carpoolService = carpoolService;
    }

    public IActionResult Index()
    {
        return RedirectToAction("List");
    }

    public async Task<IActionResult> ReceivedByCarpool(Guid id)
    {
        try
        {
            var carpool = await _carpoolService.GetCarpoolByIdAsync(id);

            if (carpool == null)
            {
                FlashMessage.SendError("Carpool not found. Could have been deleted by owner.");
                return RedirectToAction("List");
            }

            string userId = GetCurrentUser();
            if (userId != carpool.OwnerId)
            {
                FlashMessage.SendError("You are not the owner of this carpool to see its demands!");
                return RedirectToAction("List");
            }

            var demands = await _demandService.GetDemandsByCarpoolAsync(id);

            return View("List", DemandCard.GetCardsForReceiverByCarpool(demands));
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("List");
        }
    }

    [HttpGet("Demand/List")]
    public async Task<IActionResult> List()
    {
        try
        {
            var userId = GetCurrentUser();
            var user = User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? "";

            if (user == null)
            {
                FlashMessage.SendError("Error while getting your account information.");
                return RedirectToAction("Index", "Home");
            }

            var demands = await _demandService.GetDemandsBySenderAsync(userId) ?? new List<Demand>();

            return View(DemandCard.GetCardsForSender(demands));
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("Index");
        }
    }

    public async Task<IActionResult> Apply(Guid id)
    {
        try
        {
            string userId = GetCurrentUser();

            var carpool = await _carpoolService.GetCarpoolByIdAsync(id);

            if (carpool == null)
            {
                FlashMessage.SendError("The Carpool You are trying to apply doesn't exist. Probably Deleted by owner");
                return RedirectToAction("List", "Carpool");
            }

            if (!carpool.IsOpen)
            {
                FlashMessage.SendError("Can't join this Carpool. This one has closed its application");
                return RedirectToAction("List", "Carpool");
            }

            if (_demandService.IsApplied(userId, id))
            {
                FlashMessage.SendError("You have already applied for this carpool");
                return RedirectToAction("List", "Carpool");
            }

            if (carpool.OwnerId == userId)
            {
                FlashMessage.SendError("You can't apply to your own carpool!");
                return RedirectToAction("List", "Carpool");
            }

            var demand = new Demand
            {
                PassengerId = userId,
                CarpoolId = id,
                status = Demand.Response.pending,
                SubmissionTime = DateTime.Now
            };

            await _demandService.AddDemandAsync(demand);
            FlashMessage.SendSuccess("You have applied for the carpool");
            return RedirectToAction("List");
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("List");
        }
    }

    public async Task<IActionResult> Details(Guid id)
    {
        try
        {
            var demand = await _demandService.GetDemandByIdAsync(id);

            if (demand == null)
            {
                FlashMessage.SendError("The Specified Demand is not Found! Passenger may have deleted it");
                return RedirectToAction("List");
            }

            string userId = GetCurrentUser();
            if (userId != demand.PassengerId && userId != demand.Carpool.OwnerId)
            {
                FlashMessage.SendError("You are not Allowed to see this demand! Must be Sender or Receiver.");
                return RedirectToAction("List");
            }

            ViewBag.IsEditable = (userId == demand.PassengerId);
            bool receiver = userId == demand.Carpool.OwnerId;
            ViewBag.CarpoolCard = new CarpoolCard(demand.Carpool)
            {
                ByOwner = !receiver,
                Apply = !receiver && !(_demandService.IsApplied(demand.PassengerId, demand.CarpoolId)),
                SeeApplication = false,
                SeeCarpool = true,
                DemandId = demand.Id
            };

            return View(demand);
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("List");
        }
    }

    public async Task<IActionResult> Received()
    {
        try
        {
            string userId = GetCurrentUser();
            var applications = await _demandService.GetDemandsByOwnerIdAsync(userId);

            return View("List", DemandCard.GetCardsForReceiver(applications));
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("List");
        }
    }

    public async Task<IActionResult> Delete(Guid id)
    {
        try
        {
            string userId = GetCurrentUser();
            var demand = await _demandService.GetDemandByIdAsync(id);

            if (demand != null && userId == demand.PassengerId)
            {
                await _demandService.DeleteDemandAsync(id);
            }
            else
            {
                FlashMessage.SendError("You are not the author of that demand!");
            }

            return RedirectToAction("List");
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("List");
        }
    }

    public async Task<IActionResult> Accept(Guid id)
    {
        try
        {
            string userId = GetCurrentUser();
            var demand = await _demandService.GetDemandByIdAsync(id);

            if (demand == null)
            {
                FlashMessage.SendError("Demand is not found! Probably deleted by owner");
                return RedirectToAction("Received");
            }

            if (userId != demand.Carpool.OwnerId)
            {
                FlashMessage.SendError("You can't respond to this demand. It is not sent to you");
                return RedirectToAction("Received");
            }

            if (demand.status != Demand.Response.pending)
            {
                FlashMessage.SendError("You can't respond to this demand. It is already responded or cancelled");
                return RedirectToAction("Received");
            }

            if (demand.Carpool.NumberOfPlaces <= 0)
            {
                FlashMessage.SendError("There are no enough places to accept more demands");
                return RedirectToAction("Received");
            }

            demand.status = Demand.Response.accepted;
            demand.Carpool.NumberOfPlaces--;

            // TODO: needs to be discussed: if the places are full does this mean that the offer needs to be closed?
            if (demand.Carpool.NumberOfPlaces == 0)
            {
                demand.Carpool.IsOpen = false;
                FlashMessage.SendInfo("Places are full now. The Offer is closed ");
            }

            await _demandService.UpdateDemandAsync(demand);
            return RedirectToAction("Received");
        }
        catch (Exception ex)
        {
            // Handle exceptions appropriately (log, display an error page, etc.)
            FlashMessage.SendError("An error occurred while processing your request.");
            return RedirectToAction("Received");
        }
    }

    public async Task<IActionResult> Decline(Guid id)
    {
        try
        {
            string userId = GetCurrentUser();
            var demand = await _demandService.GetDemandByIdAsync(id);

            if (demand == null)
            {
                FlashMessage.SendError("Demand is not found! Probably deleted by owner");
                return RedirectToAction("Received");
            }

            if (userId != demand.Carpool.OwnerId)
            {
                FlashMessage.SendError("You can't respond to this demand. It is not sent to you");

Views/Demand/Apply.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Apply</h2>

Views/Demand/Delete.cshtml
@model CarpooliDotTN.Models.Demand

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Demand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SubmissionTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SubmissionTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carpool)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carpool.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Passenger)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Passenger.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Demand/Details.cshtml
@using CarpooliDotTN.ViewModels
@using Microsoft.AspNetCore.Mvc.Rendering

@model CarpooliDotTN.Models.Demand

@{
    ViewBag.Title = "Details";
}
<h2>Demand Detail</h2>
@if (ViewBag.IsEditable??false)
{
    <h4> You have Applied for this carpool below</h4>
    <h5> @Model.SubmissionTime</h5>
    <div class="col-lg-8">
        @Html.Partial("_CarpoolCard",(CarpoolCard) ViewBag.CarpoolCard)
    </div>
    <hr />
    if (Model.status==Demand.Response.pending){
        <p>Your demand is currently <span class="btn btn-outline-warning disabled">pending</span>. The Author of that carpool didn't answer you yet.</p>
        <p>You Can Wait for his reply, or cancel your demand (You won't be able to join again) </p>
        <br />
        <a href="@Url.Action("Cancel","Demand",new{id=Model.Id})" class="btn btn-dark"> Cancel Demand </a>
    }
    if (Model.status==Demand.Response.accepted){
        <p>Your demand has been <span class="btn btn-outline-success disabled">accepted</span>. Contact the Author of the carpool for further details.</p>
        <p>You Are still able to cancel your demand and your reservation will be freed (You won't be able to join again) </p>
        <br />
        <a href="@Url.Action("Cancel","Demand",new{id=Model.Id})" class="btn btn-dark"> Cancel Demand </a>
    }
    if (Model.status==Demand.Response.refused){
        <p>Your demand has been <span class="btn btn-outline-danger disabled">refused</span>. You won't be able to join this Carpool.</p>
    }
    if (Model.status==Demand.Response.cancelled){
        <p>You have <span class="btn btn-outline-dark disabled">cancelled</span> this demand. You won't be able to join this Carpool or send a demand again.</p>
    }
    
    
    
}
else
{
    
    <h4> You have received application for this carpool below</h4>
    <h5> @Model.SubmissionTime</h5>
    <div class="col-lg-8">
        @Html.Partial("_CarpoolCard",(CarpoolCard) ViewBag.CarpoolCard)
    </div>
    <hr />
    if (Model.status==Demand.Response.pending){
        <p>You haven't replied at this demand yet.</p>
        @if(Model.Carpool.NumberOfPlaces<=0){
            <p>There is no places left for this carpool. You can either Refuse this demand, or leave it pending until some places are free then be able to accept it</p>
        }
        else{
            <p>You can choose to accept this applicant, so he will join this carpool.</p>
            <p>Or you can choose to refuse his application, so he won't be able to join you or re-send another application</p>
        }
        <br />
        
        @if(Model.Carpool.NumberOfPlaces<=0){<a href="@Url.Action("Accept","Demand",new{id=Model.Id})" class="btn btn-dark"> Cancel Demand </a>}
        <a href="@Url.Action("Decline","Demand",new{id=Model.Id})" class="btn btn-dark"> Cancel Demand </a>
    }
    if (Model.status==Demand.Response.accepted){
        <p>You have <span class="btn btn-outline-success disabled">approved</span> this caroool demand. Contact the passenger for further details.</p>
        <br />
    
    }
    if (Model.status==Demand.Response.refused){
        <p>Your have <span class="btn btn-outline-danger disabled">refused</span> this caroool demand. The applicant can't join or re-send another demand</p>
    }
    if (Model.status==Demand.Response.cancelled){
        <p>This demand has been <span class="btn btn-outline-dark disabled">cancelled</span> by the applicant. You won't be able to respond, and  the applicant can't join or re-send another demand.</p>
    
    }
    
}

Views/Demand/List.cshtml
@model List<CarpooliDotTN.ViewModels.DemandCard>
<div class="container">
    <div class="d-flex justify-content-between">
        <h1>Demands List</h1>
    </div>
    <hr>
    <div class="card-list col-md-6 col-sm-12">
        @foreach (var item in Model)
        {
            @Html.Partial("_DemandCard", (CarpooliDotTN.ViewModels.DemandCard)item)
        }
    </div>


</div>

Views/Demand/Received.cshtml
@model IEnumerable<CarpooliDotTN.Models.Demand>

@{
    ViewData["Title"] = "Received";
}

<h1>Received</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SubmissionTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carpool)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Passenger)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SubmissionTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carpool.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passenger.FirstName) @Html.DisplayFor(modelItem => item.Passenger.LastName)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.status)
                </td>
            <td>
                    @if (item.status == Demand.Response.pending)
                    {
                        <a asp-action="Accept" asp-route-id="@item.Id">Accept</a> 
                        <a asp-action = "Decline" asp-route-id = "@item.Id" > Decline </a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>

Views/Demand/Sent.cshtml
@model List<CarpooliDotTN.ViewModels.DemandCard>
<div class="container">
    <div class="d-flex justify-content-between">
        <h1>Sent Demands</h1>
    </div>
    <hr>
    <div class="card-list col-md-6 col-sm-12">
        @foreach (var item in Model)
        {
            @Html.Partial("_DemandCard", (CarpooliDotTN.ViewModels.DemandCard)item)
        }
    </div>


</div>